services:
  postgres:
    image: postgres:15
    container_name: local_pgdb_lf
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: lastfarewells
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container_lf
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
  keycloak:
    image: quay.io/keycloak/keycloak:20.0
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/lastfarewells
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
    ports:
      - 9090:8080
    command:
      - start-dev