name: Pull Request Checks

on:
  pull_request:
    branches:
      - playlist_reorder

permissions:
  id-token: write
  security-events: write
  contents: read
  actions: read
  issues: write
  pull-requests: write
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run tests
        run: mvn -X test
        env:
          MAVEN_OPTS: "-XX:+ShowCodeDetailsInExceptionMessages"

      - name: Run SpotBugs, PMD, and Checkstyle
        run: mvn -X verify spotbugs:spotbugs pmd:pmd
        env:
          MAVEN_OPTS: "-XX:+ShowCodeDetailsInExceptionMessages"

      - name: Analyze SpotBugs results
        uses: jwgmeligmeyling/spotbugs-github-action@master
        with:
          path: "**/spotbugsXml.xml"

      - name: Analyze PMD results
        uses: jwgmeligmeyling/pmd-github-action@master
        with:
          path: "**/pmd.xml"

      - name: Generate code coverage
        run: mvn -X jacoco:report
        env:
          MAVEN_OPTS: "-XX:+ShowCodeDetailsInExceptionMessages"

      - name: Generate JaCoCo Badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: target/site/jacoco/jacoco.csv
          generate-coverage-badge: true
          coverage-badge-filename: jacoco.svg
          generate-summary: false
          summary-filename: coverage-summary.json
          workflow-summary-heading: JaCoCo Test Coverage Summary
