name: Pull Request Checks

on:
  pull_request:
    branches:
      - playlist_recorder

env:
  MVN_OPS: -DGIT_USER_NAME=${{ secrets.GIT_USER_NAME }} -DGIT_TOKEN=${{ secrets.GIT_TOKEN }} -s settings.xml
#on:
#  workflow_dispatch:
#    # Inputs the workflow accepts.
#    inputs:
#      name:
#        # Friendly description to be shown in the UI instead of 'name'
#        description: 'test run for code analysis'
#        # Default value if no value is explicitly provided
#        default: 'test'
permissions:
  id-token: write # This is required for requesting the JWT
  security-events: write
  contents: read
  actions: read # This is required for actions/checkout
  issues: write
  pull-requests: write
  checks: write # needed for spotbugs
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Run tests
        run: mvn $MVN_OPS test
      - name: Run SpotBugs, PMD and checkstyle
        run: mvn $MVN_OPS -B verify spotbugs:spotbugs pmd:pmd
      - uses: jwgmeligmeyling/spotbugs-github-action@master
        with:
          path: '**/spotbugsXml.xml'
      - uses: jwgmeligmeyling/pmd-github-action@master
        with:
          path: '**/pmd.xml'
      - name: Generate code coverage
        run: mvn jacoco:report
      - name: Generate JaCoCo Badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: target/site/jacoco/jacoco.csv
          generate-coverage-badge: true
          coverage-badge-filename: jacoco.svg
          generate-summary: false
          summary-filename: coverage-summary.json
          workflow-summary-heading: JaCoCo Test Coverage Summary
